/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CantoInterface,
  CantoInterfaceInterface,
} from "../CantoInterface";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "getPriorVotes",
    outputs: [
      {
        internalType: "uint96",
        name: "",
        type: "uint96",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class CantoInterface__factory {
  static readonly abi = _abi;
  static createInterface(): CantoInterfaceInterface {
    return new utils.Interface(_abi) as CantoInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CantoInterface {
    return new Contract(address, _abi, signerOrProvider) as CantoInterface;
  }
}
