/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  GovernorBravoDelegateStorageV2,
  GovernorBravoDelegateStorageV2Interface,
} from "../GovernorBravoDelegateStorageV2";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "canto",
    outputs: [
      {
        internalType: "contract CantoInterface",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "initialProposalId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "latestProposalIds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "pendingAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "proposalCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "proposals",
    outputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "proposer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "eta",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "canceled",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "executed",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "timelock",
    outputs: [
      {
        internalType: "contract TimelockInterface",
        name: "",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061036b806100206000396000f3fe608060405234801561001057600080fd5b50600436106100935760003560e01c80635c60da1b116100665780635c60da1b1461010f578063d33219b414610117578063da35c6641461011f578063f851a44014610127578063fc4eee421461012f57610093565b8063013cf08b1461009857806316681c07146100c557806317977c61146100da57806326782247146100fa575b600080fd5b6100ab6100a6366004610220565b610137565b6040516100bc959493929190610292565b60405180910390f35b6100cd610175565b6040516100bc9190610276565b6100ed6100e83660046101fa565b610184565b6040516100bc9190610284565b610102610196565b6040516100bc9190610268565b6101026101a5565b6100cd6101b4565b6100ed6101c3565b6101026101c9565b6100ed6101d8565b6007602081905260009182526040909120805460018201546002830154929093015490926001600160a01b0316919060ff8082169161010090041685565b6006546001600160a01b031681565b60086020526000908152604090205481565b6001546001600160a01b031681565b6002546001600160a01b031681565b6005546001600160a01b031681565b60045481565b6000546001600160a01b031681565b60035481565b80356101e981610308565b92915050565b80356101e98161031f565b60006020828403121561020c57600080fd5b600061021884846101de565b949350505050565b60006020828403121561023257600080fd5b600061021884846101ef565b610247816102de565b82525050565b610247816102e9565b610247816102fd565b610247816102fa565b602081016101e9828461023e565b602081016101e98284610256565b602081016101e9828461025f565b60a081016102a0828861025f565b6102ad602083018761023e565b6102ba604083018661025f565b6102c7606083018561024d565b6102d4608083018461024d565b9695505050505050565b60006101e9826102ee565b151590565b6001600160a01b031690565b90565b60006101e9826102de565b610311816102de565b811461031c57600080fd5b50565b610311816102fa56fea365627a7a72315820228e7ac8f2898bf50a15fe17e4dd289cfa5b18e38e4fd15cc3c1d59c0a3bcfcd6c6578706572696d656e74616cf564736f6c63430005100040";

export class GovernorBravoDelegateStorageV2__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<GovernorBravoDelegateStorageV2> {
    return super.deploy(
      overrides || {}
    ) as Promise<GovernorBravoDelegateStorageV2>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): GovernorBravoDelegateStorageV2 {
    return super.attach(address) as GovernorBravoDelegateStorageV2;
  }
  connect(signer: Signer): GovernorBravoDelegateStorageV2__factory {
    return super.connect(signer) as GovernorBravoDelegateStorageV2__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GovernorBravoDelegateStorageV2Interface {
    return new utils.Interface(_abi) as GovernorBravoDelegateStorageV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GovernorBravoDelegateStorageV2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as GovernorBravoDelegateStorageV2;
  }
}
